### ISSUE TITLE
missing startup functions

### ISSUE THREAD

**Issue by yayitswei** [dgknght/clj-money-datomic#2]
Hi, thanks for publishing `clj-money-datomic`! Following the readme, I'm trying to run

```
(clj-money.admin/init-database)
```

to initialize the database, but couldn't find the function nor the admin namespace.

**Comment by dgknght** [comment]
I'm glad you find it interesting! This is a learning project that I haven't looked at in a while, but you're welcome to use it as you please.

The quoted above can be found [here](https://github.com/dgknght/clj-money-datomic/blob/master/src/clj_money/admin.clj#L22). Maybe you'll need to require the namespace if the repl can't find it.
```
(require 'clj-money.admin)
```

**Comment by yayitswei** [comment]
Thanks, got it working!
